name: Schedule EVSE Data Refresh

on:
  schedule:
    - cron: '0 8 * * 1' # every monday at 8:00 AM
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary  # Add any other dependencies
          pip install requests 

      - name: Run Python script
        run: python hello.py  # Replace with your script path
